version: "1.0"
info:
  model: int-scaffold
packages:
- name: Demo2Dec1Project
  gitServerName: DemoDec1
  gitUrl: https://github.com/vijetadixit/Demo2Dec1Project
  gitUsername: vijetadixit
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: vidi21Nov
  gitUrl: https://github.com/vijetadixit
  gitUsername: vijetadixit
  gitBranch: Test
